<a href="https://colab.research.google.com/github/zxqw6634/ai/blob/master/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

x = np.linspace(2.0, 3.0, num=5)

y = np.linspace(2.0, 3.0, num=5, endpoint=False)

z = np.linspace(2.0, 3.0, num=5, retstep=True)

print(x)
print(y)
print(z)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [0]:
import numpy as np

x = np.arange(24).reshape(3,4,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
import numpy as np

x = np.arange(24).reshape(4,3,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar


array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [0]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar.ravel()



array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [0]:
ar=np.array([np.arange(1,6),np.arange(10,15)]);
ar.T.ravel()


array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])